seed: 42
experiment: default
data:
  train_csv: data/raw/train.csv
  test_csv: data/raw/test.csv
split:
  train_size: 0.7
  valid_size: 0.15
model:
  type: xgboost
  params:
    max_depth: 6
    n_estimators: 200
    learning_rate: 0.1

